### ISSUE TITLE
F-Droid installation instructions are mixed up between 1st and 2nd generation?

### ISSUE THREAD

**Issue by arthow4n** [ntherning/StorytelReaderMods#10]
Hej!

In the F-Droid installation instructions it referred 1st generation device to install `F-Droid.apk` and 2nd generation device to install `org.fdroid.fdroid_1012051.apk`, I believe it actually should be the opposite.

With a 2nd generation device, when I installed `org.fdroid.fdroid_1012051.apk`, the installation worked, but then the installed F-Droid failed to update the repo index. Installing the latest version `F-Droid.apk` instead worked well.

I suppose F-Droid changed something so old version no longer works, I'm unsure though. Perhaps 1st generation device users no longer have a good store option?

**Comment by ntherning** [comment]
The README has now been updated to address this issue (see #12). Thanks for the report! `org.fdroid.fdroid_1012051.apk` is the last version of F-Droid which supports Android 4.2.2 which the 1st gen is based on.
